/*
** EPITECH PROJECT, 2021
** ${FOLDER_NAME}
** File description:
** syscalls.h file
*/

#ifndef C_SYSCALLS_H
#define C_SYSCALLS_H

#include <sys/ptrace.h>
#include <unistd.h>
#include <stdio.h>
#include <syscalls.h>
#include <sys/user.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>

typedef struct syscall_s syscall_t;

enum types {
    NUMBER,
    POINTER,
    STRING
};

struct syscall_s {
    char *name;
    int nbr_args;
    enum types return_type;
    enum types arg_type[6];
};

static syscall_t syscall_entries[] = {
    {
        .return_type = NUMBER,
        .name = "read",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "write",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "open",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "close",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "stat",
        .arg_type = {STRING, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "fstat",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "lstat",
        .arg_type = {STRING, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "poll",
        .arg_type = {POINTER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "lseek",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = POINTER,
        .name = "mmap",
        .arg_type = {POINTER, NUMBER, NUMBER, NUMBER, NUMBER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "mprotect",
        .arg_type = {POINTER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "munmap",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "brk",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "rt_sigaction",
        .arg_type = {NUMBER, POINTER, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "rt_sigprocmask",
        .arg_type = {NUMBER, POINTER, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "rt_sigreturn",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "ioctl",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "pread64",
        .arg_type = {NUMBER, STRING, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "pwrite64",
        .arg_type = {NUMBER, STRING, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "readv",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "writev",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "access",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "pipe",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "select",
        .arg_type = {NUMBER, POINTER, POINTER, POINTER, POINTER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "sched_yield",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "mremap",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "msync",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "mincore",
        .arg_type = {NUMBER, NUMBER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "madvise",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "shmget",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "shmat",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "shmctl",
        .arg_type = {NUMBER, NUMBER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "dup",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "dup2",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "pause",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "nanosleep",
        .arg_type = {POINTER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "getitimer",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "alarm",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "setitimer",
        .arg_type = {NUMBER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "getpid",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "sendfile",
        .arg_type = {NUMBER, NUMBER, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "socket",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "connect",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "accept",
        .arg_type = {NUMBER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "sendto",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, POINTER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "recvfrom",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "sendmsg",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "recvmsg",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "shutdown",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "bind",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "listen",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "getsockname",
        .arg_type = {NUMBER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "getpeername",
        .arg_type = {NUMBER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "socketpair",
        .arg_type = {NUMBER, NUMBER, NUMBER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "setsockopt",
        .arg_type = {NUMBER, NUMBER, NUMBER, STRING, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "getsockopt",
        .arg_type = {NUMBER, NUMBER, NUMBER, STRING, POINTER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "clone",
        .arg_type = {NUMBER, NUMBER, POINTER, POINTER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "fork",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "vfork",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "execve",
        .arg_type = {STRING, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "exit",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "wait4",
        .arg_type = {NUMBER, POINTER, NUMBER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "kill",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "uname",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "semget",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "semop",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "semctl",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "shmdt",
        .arg_type = {STRING, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "msgget",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "msgsnd",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "msgrcv",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "msgctl",
        .arg_type = {NUMBER, NUMBER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "fcntl",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "flock",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "fsync",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "fdatasync",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "truncate",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "ftruncate",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "getdents",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "getcwd",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "chdir",
        .arg_type = {STRING, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "fchdir",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "rename",
        .arg_type = {STRING, STRING, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "mkdir",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "rmdir",
        .arg_type = {STRING, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "creat",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "link",
        .arg_type = {STRING, STRING, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "unlink",
        .arg_type = {STRING, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "symlink",
        .arg_type = {STRING, STRING, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "readlink",
        .arg_type = {STRING, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "chmod",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "fchmod",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "chown",
        .arg_type = {STRING, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "fchown",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "lchown",
        .arg_type = {STRING, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "umask",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "gettimeofday",
        .arg_type = {POINTER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "getrlimit",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "getrusage",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "sysinfo",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "times",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "ptrace",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "getuid",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "syslog",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "getgid",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "setuid",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "setgid",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "geteuid",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "getegid",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "setpgid",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "getppid",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "getpgrp",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "setsid",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "setreuid",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "setregid",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "getgroups",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "setgroups",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "setresuid",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "getresuid",
        .arg_type = {POINTER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "setresgid",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "getresgid",
        .arg_type = {POINTER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "getpgid",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "setfsuid",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "setfsgid",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "getsid",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "capget",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "capset",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "rt_sigpending",
        .arg_type = {POINTER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "rt_sigtimedwait",
        .arg_type = {POINTER, POINTER, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "rt_sigqueueinfo",
        .arg_type = {NUMBER, NUMBER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "rt_sigsuspend",
        .arg_type = {POINTER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "sigaltstack",
        .arg_type = {POINTER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "utime",
        .arg_type = {STRING, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "mknod",
        .arg_type = {STRING, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "uselib",
        .arg_type = {STRING, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "personality",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "ustat",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "statfs",
        .arg_type = {STRING, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "fstatfs",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "sysfs",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "getpriority",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "setpriority",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "sched_setparam",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "sched_getparam",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "sched_setscheduler",
        .arg_type = {NUMBER, NUMBER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "sched_getscheduler",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "sched_get_priority_max",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "sched_get_priority_min",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "sched_rr_get_interval",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "mlock",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "munlock",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "mlockall",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "munlockall",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "vhangup",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "modify_ldt",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "pivot_root",
        .arg_type = {STRING, STRING, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "_sysctl",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "prctl",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "arch_prctl",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "adjtimex",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "setrlimit",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "chroot",
        .arg_type = {STRING, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "sync",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "acct",
        .arg_type = {STRING, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "settimeofday",
        .arg_type = {POINTER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "mount",
        .arg_type = {STRING, STRING, STRING, NUMBER, POINTER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "umount2",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "swapon",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "swapoff",
        .arg_type = {STRING, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "reboot",
        .arg_type = {NUMBER, NUMBER, NUMBER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "sethostname",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "setdomainname",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "iopl",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "ioperm",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "create_module",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "init_module",
        .arg_type = {POINTER, NUMBER, STRING, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "delete_module",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "get_kernel_syms",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "query_module",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "quotactl",
        .arg_type = {NUMBER, STRING, NUMBER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "nfsservctl",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "getpmsg",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "putpmsg",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "afs_syscall",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "tuxcall",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "security",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "gettid",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "readahead",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "setxattr",
        .arg_type = {STRING, STRING, POINTER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "lsetxattr",
        .arg_type = {STRING, STRING, POINTER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "fsetxattr",
        .arg_type = {NUMBER, STRING, POINTER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "getxattr",
        .arg_type = {STRING, STRING, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "lgetxattr",
        .arg_type = {STRING, STRING, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "fgetxattr",
        .arg_type = {NUMBER, STRING, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "listxattr",
        .arg_type = {STRING, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "llistxattr",
        .arg_type = {STRING, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "flistxattr",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "removexattr",
        .arg_type = {STRING, STRING, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "lremovexattr",
        .arg_type = {STRING, STRING, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "fremovexattr",
        .arg_type = {NUMBER, STRING, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "tkill",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "time",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "futex",
        .arg_type = {POINTER, NUMBER, NUMBER, POINTER, POINTER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "sched_setaffinity",
        .arg_type = {NUMBER, NUMBER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "sched_getaffinity",
        .arg_type = {NUMBER, NUMBER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "set_thread_area",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "io_setup",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "io_destroy",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "io_getevents",
        .arg_type = {NUMBER, NUMBER, NUMBER, POINTER, POINTER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "io_submit",
        .arg_type = {NUMBER, NUMBER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "io_cancel",
        .arg_type = {NUMBER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "get_thread_area",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "lookup_dcookie",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "epoll_create",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "epoll_ctl_old",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "epoll_wait_old",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "remap_file_pages",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "getdents64",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "set_tid_address",
        .arg_type = {POINTER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "restart_syscall",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "semtimedop",
        .arg_type = {NUMBER, POINTER, NUMBER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "fadvise64",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "timer_create",
        .arg_type = {NUMBER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "timer_settime",
        .arg_type = {NUMBER, NUMBER, POINTER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "timer_gettime",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "timer_getoverrun",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "timer_delete",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "clock_settime",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "clock_gettime",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "clock_getres",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "clock_nanosleep",
        .arg_type = {NUMBER, NUMBER, POINTER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "exit_group",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "epoll_wait",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "epoll_ctl",
        .arg_type = {NUMBER, NUMBER, NUMBER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "tgkill",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "utimes",
        .arg_type = {STRING, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "vserver",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "mbind",
        .arg_type = {NUMBER, NUMBER, NUMBER, POINTER, NUMBER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "set_mempolicy",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "get_mempolicy",
        .arg_type = {POINTER, POINTER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "mq_open",
        .arg_type = {STRING, NUMBER, NUMBER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "mq_unlink",
        .arg_type = {STRING, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "mq_timedsend",
        .arg_type = {NUMBER, STRING, NUMBER, NUMBER, POINTER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "mq_timedreceive",
        .arg_type = {NUMBER, STRING, NUMBER, POINTER, POINTER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "mq_notify",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "mq_getsetattr",
        .arg_type = {NUMBER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "kexec_load",
        .arg_type = {NUMBER, NUMBER, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "waitid",
        .arg_type = {NUMBER, NUMBER, POINTER, NUMBER, POINTER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "add_key",
        .arg_type = {STRING, STRING, POINTER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "request_key",
        .arg_type = {STRING, STRING, STRING, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "keyctl",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "ioprio_set",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "ioprio_get",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "inotify_init",
        .arg_type = {0, 0, 0, 0, 0, 0},
        .nbr_args = 0,
    },
    {
        .return_type = NUMBER,
        .name = "inotify_add_watch",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "inotify_rm_watch",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "migrate_pages",
        .arg_type = {NUMBER, NUMBER, POINTER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "openat",
        .arg_type = {NUMBER, STRING, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "mkdirat",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "mknodat",
        .arg_type = {NUMBER, STRING, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "fchownat",
        .arg_type = {NUMBER, STRING, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "futimesat",
        .arg_type = {NUMBER, STRING, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "newfstatat",
        .arg_type = {NUMBER, STRING, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "unlinkat",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "renameat",
        .arg_type = {NUMBER, STRING, NUMBER, STRING, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "linkat",
        .arg_type = {NUMBER, STRING, NUMBER, STRING, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "symlinkat",
        .arg_type = {STRING, NUMBER, STRING, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "readlinkat",
        .arg_type = {NUMBER, STRING, STRING, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "fchmodat",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "faccessat",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "pselect6",
        .arg_type = {NUMBER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "ppoll",
        .arg_type = {POINTER, NUMBER, POINTER, POINTER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "unshare",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "set_robust_list",
        .arg_type = {POINTER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "get_robust_list",
        .arg_type = {NUMBER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "splice",
        .arg_type = {NUMBER, POINTER, NUMBER, POINTER, NUMBER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "tee",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "sync_file_range",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "vmsplice",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "move_pages",
        .arg_type = {NUMBER, NUMBER, POINTER, POINTER, POINTER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "utimensat",
        .arg_type = {NUMBER, STRING, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "epoll_pwait",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, POINTER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "signalfd",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "timerfd_create",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "eventfd",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "fallocate",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "timerfd_settime",
        .arg_type = {NUMBER, NUMBER, POINTER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "timerfd_gettime",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "accept4",
        .arg_type = {NUMBER, POINTER, POINTER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "signalfd4",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "eventfd2",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "epoll_create1",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "dup3",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "pipe2",
        .arg_type = {POINTER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "inotify_init1",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "preadv",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "pwritev",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "rt_tgsigqueueinfo",
        .arg_type = {NUMBER, NUMBER, NUMBER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "perf_event_open",
        .arg_type = {POINTER, NUMBER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "recvmmsg",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, POINTER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "fanotify_init",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "fanotify_mark",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, STRING, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "prlimit64",
        .arg_type = {NUMBER, NUMBER, POINTER, POINTER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "name_to_handle_at",
        .arg_type = {NUMBER, STRING, POINTER, POINTER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "open_by_handle_at",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "clock_adjtime",
        .arg_type = {NUMBER, POINTER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "syncfs",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "sendmmsg",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "setns",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "getcpu",
        .arg_type = {POINTER, POINTER, POINTER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "process_vm_readv",
        .arg_type = {NUMBER, POINTER, NUMBER, POINTER, NUMBER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "process_vm_writev",
        .arg_type = {NUMBER, POINTER, NUMBER, POINTER, NUMBER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "kcmp",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "finit_module",
        .arg_type = {NUMBER, STRING, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "sched_setattr",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "sched_getattr",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "renameat2",
        .arg_type = {NUMBER, STRING, NUMBER, STRING, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "seccomp",
        .arg_type = {NUMBER, NUMBER, STRING, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "getrandom",
        .arg_type = {POINTER, POINTER, POINTER, POINTER, POINTER, POINTER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "memfd_create",
        .arg_type = {STRING, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "kexec_file_load",
        .arg_type = {NUMBER, NUMBER, NUMBER, STRING, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "bpf",
        .arg_type = {NUMBER, POINTER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "execveat",
        .arg_type = {NUMBER, STRING, POINTER, POINTER, NUMBER, 0},
        .nbr_args = 5,
    },
    {
        .return_type = NUMBER,
        .name = "userfaultfd",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    },
    {
        .return_type = NUMBER,
        .name = "membarrier",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "mlock2",
        .arg_type = {NUMBER, NUMBER, NUMBER, 0, 0, 0},
        .nbr_args = 3,
    },
    {
        .return_type = NUMBER,
        .name = "copy_file_range",
        .arg_type = {NUMBER, POINTER, NUMBER, POINTER, NUMBER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "preadv2",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, NUMBER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "pwritev2",
        .arg_type = {NUMBER, POINTER, NUMBER, NUMBER, NUMBER, NUMBER},
        .nbr_args = 6,
    },
    {
        .return_type = NUMBER,
        .name = "pkey_mprotect",
        .arg_type = {NUMBER, NUMBER, NUMBER, NUMBER, 0, 0},
        .nbr_args = 4,
    },
    {
        .return_type = NUMBER,
        .name = "pkey_alloc",
        .arg_type = {NUMBER, NUMBER, 0, 0, 0, 0},
        .nbr_args = 2,
    },
    {
        .return_type = NUMBER,
        .name = "pkey_free",
        .arg_type = {NUMBER, 0, 0, 0, 0, 0},
        .nbr_args = 1,
    }
};

#endif //C_SYSCALLS_H
